from tkinter import *
from PIL import Image, ImageTk  # pip install pillow
root = Tk()
# user_img = PhotoImage(file="user.png")
f = Image.open("user.png")
img = ImageTk.PhotoImage(f)
frame1 = Frame(root)
frame1.pack(pady=15)
my_label = Label(frame1, text="username", image=img, compound="left")
my_label.pack(side=LEFT)
user_input = Entry(frame1,highlightthickness=3, highlightcolor="red", highlightbackground="gray")
user_input.pack(side=LEFT)
f2 = Image.open("pass.png")
f2 = f2.resize((16,16))
img2 = ImageTk.PhotoImage(f2)
frame2 = Frame(root)
frame2.pack(pady=15)
my_label = Label(frame2, text="password", image=img2, compound="left")
my_label.pack(side=LEFT)
user_input = Entry(frame2,highlightthickness=3, highlightcolor="red", highlightbackground="gray")
user_input.pack(side=LEFT)
f3 = Image.open("pass.png")
img3 = ImageTk.PhotoImage(f2)
submit_button = Button(root, text="ورود", image=img3, compound="right", width=90, height=70, bg="lightblue")
submit_button.pack()
root.mainloop()